version: 2
jobs:
  build:
    docker:
      - image: debian:stretch-slim
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y build-essential
            apt-get install -y git
      - run:
          name: Checkout source
          command: |
            git clone https://${GITHUB_PERSONAL_TOKEN}@github.com/morgrimm/repo.git .
            git submodule sync
            git submodule update --init
            git checkout ${CIRCLE_BRANCH}
      - run:
          name: Configure author
          command: |  
            git config credential.helper 'cache --timeout=120'
            git config user.name "CirclCI"
      - run:
          name: Clean
          command: make clean
      - run:
          name: Build packages
          command: make debs
      - run:
          name: Generate depictions
          command: make depictions
      - run:
          name: Generate release
          command: make Release
      - run:
          name: Push release
          command: |
            git add -A
            git commit -m "RELEASE by CircleCI"
            git push -q
